export const siteConfig = {
  name: process.env.NEXT_PUBLIC_SITE_NAME ?? "Finbrief",
  shortName: "FB",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  description:
    "Plain-language guidance, tools, and personalized recommendations to help you budget, invest, and save smarter.",
  tagline: "Budget. Invest. Save smarter.",
  twitter: "@finbrief",
  pillars: [
    { slug: "budget", label: "Budget" },
    { slug: "invest", label: "Invest" },
    { slug: "save-tax", label: "Save tax" },
    { slug: "borrow-smart", label: "Borrow smart" },
    { slug: "protect", label: "Protect" },
  ] as const,
  tools: [
    { slug: "budget-50-30-20", label: "50/30/20 budget", pillar: "Budget" },
    { slug: "401k-match", label: "401(k) match", pillar: "Invest" },
    { slug: "tax-bracket", label: "Marginal tax rate", pillar: "Save tax" },
    { slug: "roth-vs-traditional", label: "Roth vs. Traditional IRA", pillar: "Invest" },
    { slug: "life-insurance", label: "Life insurance need", pillar: "Protect" },
  ] as const,
  articles: [
    {
      slug: "how-to-budget-50-30-20",
      title: "How to Budget Using the 50/30/20 Rule",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "50/30/20 budget",
      publishedAt: "2026-05-17",
      updatedAt: "2026-05-17",
    },
    {
      slug: "roth-ira-vs-traditional-ira",
      title: "Roth IRA vs. Traditional IRA: Which Should You Choose?",
      pillar: "Invest",
      tool: "roth-vs-traditional",
      keyword: "roth ira vs traditional ira",
      publishedAt: "2026-05-17",
      updatedAt: "2026-05-17",
    },
    {
      slug: "best-hysa-2026",
      title: "Best high-yield savings accounts 2026",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "best HYSA",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "how-to-invest-1000-beginners",
      title: "How to invest $1,000 for beginners",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how to invest $1,000",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "best-term-life-insurance-young-professionals",
      title: "Best term life insurance for young professionals",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "term life insurance young professionals",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "how-to-build-credit-from-scratch",
      title: "How to build credit from scratch",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "how to build credit",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "best-travel-credit-cards-2026",
      title: "Best travel credit cards 2026",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best travel credit cards",
      publishedAt: "2026-05-20",
      updatedAt: "2026-05-20",
    },
    {
      slug: "roth-ira-contribution-limits-2026",
      title: "Roth IRA contribution limits 2026",
      pillar: "Save tax",
      tool: "roth-vs-traditional",
      keyword: "roth ira contribution limits 2026",
      publishedAt: "2026-05-20",
      updatedAt: "2026-05-20",
    },
    {
      slug: "tax-loss-harvesting-guide",
      title: "Tax-loss harvesting: How it works and how to do it right",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "tax loss harvesting",
      publishedAt: "2026-05-20",
      updatedAt: "2026-05-20",
    },
    {
      slug: "401k-vs-ira-which-first",
      title: "401(k) vs. IRA: Which should you fund first?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "401k vs ira which first",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "term-vs-whole-life-insurance",
      title: "Term vs. whole life insurance: Which do you actually need?",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "term vs whole life insurance",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "how-to-build-emergency-fund",
      title: "How to build an emergency fund (step by step)",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "emergency fund",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "couples-budgeting-guide",
      title: "How to budget as a couple: A practical guide",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "couples budget",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "best-cashback-credit-cards-2026",
      title: "Best cashback credit cards 2026",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best cashback credit cards",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "how-much-life-insurance-do-i-need",
      title: "How much life insurance do I need?",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "how much life insurance do i need",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "best-brokerage-accounts-beginners",
      title: "Best brokerage accounts for beginners (2026)",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "best brokerage accounts for beginners",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "backdoor-roth-ira-guide",
      title: "Backdoor Roth IRA: A step-by-step guide for high earners (2026)",
      pillar: "Save tax",
      tool: "roth-vs-traditional",
      keyword: "backdoor roth ira",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "how-much-to-contribute-to-401k",
      title: "How much should I contribute to my 401(k)? (2026)",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how much should i contribute to 401k",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "debt-snowball-vs-avalanche",
      title: "Debt snowball vs. avalanche: Which pays off debt faster?",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "debt snowball vs avalanche",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "tax-brackets-2026",
      title: "Federal income tax brackets 2026: Complete IRS tables",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "federal income tax brackets 2026",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "best-tax-software-2026",
      title: "Best tax software 2026: TurboTax, TaxAct, and FreeTaxUSA compared",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "best tax software 2026",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "how-to-file-taxes-for-free",
      title: "How to file your taxes for free (2026 guide)",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "how to file taxes for free",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "turbotax-vs-taxact",
      title: "TurboTax vs. TaxAct: Which tax software is right for you?",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "turbotax vs taxact",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "freetaxusa-review",
      title: "FreeTaxUSA review 2026: Is the cheapest tax software any good?",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "freetaxusa review",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "hsa-vs-fsa",
      title: "HSA vs. FSA: Which one should you pick? (2026)",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "hsa vs fsa",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "hsa-as-retirement-account",
      title: "The HSA as a stealth retirement account (2026 strategy)",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "hsa retirement account",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "best-hsa-providers",
      title: "Best HSA providers 2026: Fidelity, Lively, and HealthEquity compared",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "best hsa providers",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "robinhood-review",
      title: "Robinhood review 2026: Is it actually any good?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "robinhood review",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "best-credit-cards-for-beginners",
      title: "Best credit cards for beginners (2026)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best credit cards for beginners",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "chase-sapphire-preferred-review",
      title: "Chase Sapphire Preferred review (2026): Worth the $95 fee?",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "chase sapphire preferred review",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "how-to-pay-off-credit-card-debt",
      title: "How to pay off credit card debt fast (2026 playbook)",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "how to pay off credit card debt",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "capital-gains-tax-2026",
      title: "Capital gains tax 2026: Short-term vs. long-term rates explained",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "capital gains tax 2026",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "how-much-do-i-need-to-retire",
      title: "How much do I need to retire? (2026)",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how much do i need to retire",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "what-affects-your-credit-score",
      title: "What affects your credit score? The 5 factors explained",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "what affects credit score",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "best-life-insurance-companies-2026",
      title: "Best life insurance companies 2026",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "best life insurance companies",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "best-personal-loans-2026",
      title: "Best personal loans 2026: Lowest rates and who they fit",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best personal loans",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "best-car-insurance-companies-2026",
      title: "Best car insurance companies 2026",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "best car insurance companies",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "how-to-get-a-mortgage",
      title: "How to get a mortgage (2026 step-by-step guide)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "how to get a mortgage",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "fidelity-vs-schwab",
      title: "Fidelity vs. Charles Schwab: Which brokerage wins in 2026?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "fidelity vs schwab",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "best-budgeting-apps-2026",
      title: "Best budgeting apps 2026: YNAB, Monarch, Copilot, and more",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "best budgeting apps",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "fire-movement-guide",
      title: "The FIRE movement explained: Financial independence, retire early",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "fire movement",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "mega-backdoor-roth-guide",
      title: "Mega backdoor Roth: The high-earner's $70K loophole (2026)",
      pillar: "Save tax",
      tool: "roth-vs-traditional",
      keyword: "mega backdoor roth",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "how-to-invest-in-stocks",
      title: "How to invest in stocks: A beginner's guide for 2026",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how to invest in stocks",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "amex-gold-card-review",
      title: "Amex Gold Card review (2026): Is the $325 fee worth it?",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "amex gold card review",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "how-to-budget",
      title: "How to budget: A practical guide for 2026",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "how to budget",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "credit-utilization-ratio",
      title: "Credit utilization ratio: What it is and how to lower it",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "credit utilization ratio",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "when-to-refinance-mortgage",
      title: "When to refinance your mortgage (2026 guide)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "when to refinance mortgage",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "personal-loan-vs-credit-card",
      title: "Personal loan vs. credit card: Which should you use?",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "personal loan vs credit card",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "best-business-credit-cards",
      title: "Best business credit cards 2026",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best business credit cards",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "how-credit-cards-work",
      title: "How credit cards work: A plain-English explainer",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "how credit cards work",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "vanguard-vs-fidelity",
      title: "Vanguard vs. Fidelity: Which brokerage is right for you?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "vanguard vs fidelity",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "webull-review",
      title: "Webull review 2026: Is it the right brokerage for you?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "webull review",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "hmo-vs-ppo-vs-hdhp",
      title: "HMO vs. PPO vs. HDHP: How to pick a health plan",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "hmo vs ppo vs hdhp",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "standard-vs-itemized-deduction",
      title: "Standard vs. itemized deduction: Which should you take?",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "standard vs itemized deduction",
      publishedAt: "2026-06-01",
      updatedAt: "2026-06-01",
    },
    {
      slug: "how-to-lower-car-insurance",
      title: "How to lower your car insurance (15 honest moves)",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "how to lower car insurance",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "tax-loss-harvesting-wash-sale-rule",
      title: "The wash sale rule: How to harvest losses without violating it",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "wash sale rule",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "best-credit-cards-for-fair-credit",
      title: "Best credit cards for fair credit (2026)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best credit cards for fair credit",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "student-loan-refinance",
      title: "Student loan refinance: When it makes sense (and when it doesn't)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "student loan refinance",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "how-to-pay-off-debt",
      title: "How to pay off debt: A complete 2026 playbook",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "how to pay off debt",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "tax-deductions-checklist",
      title: "2026 tax deductions checklist: 30+ commonly missed items",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "tax deductions checklist",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "best-student-credit-cards",
      title: "Best student credit cards (2026)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best student credit cards",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "how-to-stop-living-paycheck-to-paycheck",
      title: "How to stop living paycheck to paycheck (a real plan)",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "how to stop living paycheck to paycheck",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "how-much-car-insurance-do-i-need",
      title: "How much car insurance do I need? (2026 coverage guide)",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "how much car insurance do i need",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "how-to-check-credit-score-for-free",
      title: "How to check your credit score for free (6 legitimate ways)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "how to check credit score for free",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "sofi-personal-loan-review",
      title: "SoFi personal loan review (2026): Honest pros and cons",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "sofi personal loan review",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "short-vs-long-term-capital-gains",
      title: "Short-term vs. long-term capital gains: The 1-year line",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "short vs long term capital gains",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "how-much-should-emergency-fund-be",
      title: "How big should your emergency fund be? (2026 sizing guide)",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "how much should emergency fund be",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "how-to-save-money-fast",
      title: "How to save money fast: 25 moves that actually work",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "how to save money fast",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "debt-consolidation-loan",
      title: "Debt consolidation loan: When it's the right move (and when it isn't)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "debt consolidation loan",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "when-to-hire-a-cpa",
      title: "When to hire a CPA (and when tax software is enough)",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "when to hire a cpa",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "dollar-cost-averaging-vs-lump-sum",
      title: "Dollar-cost averaging vs. lump sum: What the data actually says",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "dollar cost averaging vs lump sum",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "roth-conversion-ladder",
      title: "The Roth conversion ladder: How early retirees access pre-tax money",
      pillar: "Save tax",
      tool: "roth-vs-traditional",
      keyword: "roth conversion ladder",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "how-to-choose-a-financial-advisor",
      title: "How to choose a financial advisor (and when you don't need one)",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how to choose a financial advisor",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "renters-vs-homeowners-insurance",
      title: "Renters vs. homeowners insurance: What each covers",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "renters vs homeowners insurance",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "secure-2-0-changes-2026",
      title: "SECURE 2.0 changes that take effect in 2026",
      pillar: "Save tax",
      tool: "401k-match",
      keyword: "secure 2.0 changes 2026",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "when-to-take-social-security",
      title: "When to take Social Security: The 62 vs. 67 vs. 70 decision",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "when to take social security",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "medicare-basics-2026",
      title: "Medicare basics: Parts A, B, C, D explained (2026)",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "medicare basics",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "mutual-funds-vs-etfs",
      title: "Mutual funds vs. ETFs: Which should you buy?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "mutual funds vs etfs",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "asset-allocation-by-age",
      title: "Asset allocation by age: A practical glide path",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "asset allocation by age",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "ira-rmd-rules",
      title: "IRA Required Minimum Distributions (RMDs): The 2026 rules",
      pillar: "Save tax",
      tool: "401k-match",
      keyword: "ira rmd rules",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "qualified-vs-ordinary-dividends",
      title: "Qualified vs. ordinary dividends: How each is taxed",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "qualified vs ordinary dividends",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "identity-theft-protection",
      title: "Identity theft protection: The free steps that matter most",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "identity theft protection",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "long-term-care-insurance",
      title: "Long-term care insurance: Do you actually need it?",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "long term care insurance",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
    {
      slug: "roth-ira-5-year-rules",
      title: "The Roth IRA 5-year rules: Two clocks you need to track",
      pillar: "Save tax",
      tool: "roth-vs-traditional",
      keyword: "roth ira 5 year rule",
      publishedAt: "2026-06-02",
      updatedAt: "2026-06-02",
    },
  ] as const,
};
