export const siteConfig = {
  name: process.env.NEXT_PUBLIC_SITE_NAME ?? "Finbrief",
  shortName: "FB",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  description:
    "Plain-language guidance, tools, and personalized recommendations to help you budget, invest, and save smarter.",
  tagline: "Budget. Invest. Save smarter.",
  twitter: "@finbrief",
  pillars: [
    { slug: "budget", label: "Budget" },
    { slug: "invest", label: "Invest" },
    { slug: "save-tax", label: "Save tax" },
    { slug: "borrow-smart", label: "Borrow smart" },
    { slug: "protect", label: "Protect" },
  ] as const,
  tools: [
    { slug: "budget-50-30-20", label: "50/30/20 budget", pillar: "Budget" },
    { slug: "401k-match", label: "401(k) match", pillar: "Invest" },
    { slug: "tax-bracket", label: "Marginal tax rate", pillar: "Save tax" },
    { slug: "roth-vs-traditional", label: "Roth vs. Traditional IRA", pillar: "Invest" },
    { slug: "life-insurance", label: "Life insurance need", pillar: "Protect" },
  ] as const,
  articles: [
    {
      slug: "how-to-budget-50-30-20",
      title: "How to Budget Using the 50/30/20 Rule",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "50/30/20 budget",
      publishedAt: "2026-05-17",
      updatedAt: "2026-05-17",
    },
    {
      slug: "roth-ira-vs-traditional-ira",
      title: "Roth IRA vs. Traditional IRA: Which Should You Choose?",
      pillar: "Invest",
      tool: "roth-vs-traditional",
      keyword: "roth ira vs traditional ira",
      publishedAt: "2026-05-17",
      updatedAt: "2026-05-17",
    },
    {
      slug: "best-hysa-2026",
      title: "Best high-yield savings accounts 2026",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "best HYSA",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "how-to-invest-1000-beginners",
      title: "How to invest $1,000 for beginners",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how to invest $1,000",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "best-term-life-insurance-young-professionals",
      title: "Best term life insurance for young professionals",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "term life insurance young professionals",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "how-to-build-credit-from-scratch",
      title: "How to build credit from scratch",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "how to build credit",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "best-travel-credit-cards-2026",
      title: "Best travel credit cards 2026",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best travel credit cards",
      publishedAt: "2026-05-20",
      updatedAt: "2026-05-20",
    },
    {
      slug: "roth-ira-contribution-limits-2026",
      title: "Roth IRA contribution limits 2026",
      pillar: "Save tax",
      tool: "roth-vs-traditional",
      keyword: "roth ira contribution limits 2026",
      publishedAt: "2026-05-20",
      updatedAt: "2026-05-20",
    },
    {
      slug: "tax-loss-harvesting-guide",
      title: "Tax-loss harvesting: How it works and how to do it right",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "tax loss harvesting",
      publishedAt: "2026-05-20",
      updatedAt: "2026-05-20",
    },
    {
      slug: "401k-vs-ira-which-first",
      title: "401(k) vs. IRA: Which should you fund first?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "401k vs ira which first",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "term-vs-whole-life-insurance",
      title: "Term vs. whole life insurance: Which do you actually need?",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "term vs whole life insurance",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "how-to-build-emergency-fund",
      title: "How to build an emergency fund (step by step)",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "emergency fund",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "couples-budgeting-guide",
      title: "How to budget as a couple: A practical guide",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "couples budget",
      publishedAt: "2026-05-21",
      updatedAt: "2026-05-21",
    },
    {
      slug: "best-cashback-credit-cards-2026",
      title: "Best cashback credit cards 2026",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best cashback credit cards",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "how-much-life-insurance-do-i-need",
      title: "How much life insurance do I need?",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "how much life insurance do i need",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "best-brokerage-accounts-beginners",
      title: "Best brokerage accounts for beginners (2026)",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "best brokerage accounts for beginners",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "backdoor-roth-ira-guide",
      title: "Backdoor Roth IRA: A step-by-step guide for high earners (2026)",
      pillar: "Save tax",
      tool: "roth-vs-traditional",
      keyword: "backdoor roth ira",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "how-much-to-contribute-to-401k",
      title: "How much should I contribute to my 401(k)? (2026)",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how much should i contribute to 401k",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "debt-snowball-vs-avalanche",
      title: "Debt snowball vs. avalanche: Which pays off debt faster?",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "debt snowball vs avalanche",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "tax-brackets-2026",
      title: "Federal income tax brackets 2026: Complete IRS tables",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "federal income tax brackets 2026",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "best-tax-software-2026",
      title: "Best tax software 2026: TurboTax, TaxAct, and FreeTaxUSA compared",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "best tax software 2026",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "how-to-file-taxes-for-free",
      title: "How to file your taxes for free (2026 guide)",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "how to file taxes for free",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "turbotax-vs-taxact",
      title: "TurboTax vs. TaxAct: Which tax software is right for you?",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "turbotax vs taxact",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "freetaxusa-review",
      title: "FreeTaxUSA review 2026: Is the cheapest tax software any good?",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "freetaxusa review",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "hsa-vs-fsa",
      title: "HSA vs. FSA: Which one should you pick? (2026)",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "hsa vs fsa",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "hsa-as-retirement-account",
      title: "The HSA as a stealth retirement account (2026 strategy)",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "hsa retirement account",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "best-hsa-providers",
      title: "Best HSA providers 2026: Fidelity, Lively, and HealthEquity compared",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "best hsa providers",
      publishedAt: "2026-05-30",
      updatedAt: "2026-05-30",
    },
    {
      slug: "robinhood-review",
      title: "Robinhood review 2026: Is it actually any good?",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "robinhood review",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "best-credit-cards-for-beginners",
      title: "Best credit cards for beginners (2026)",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "best credit cards for beginners",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "chase-sapphire-preferred-review",
      title: "Chase Sapphire Preferred review (2026): Worth the $95 fee?",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "chase sapphire preferred review",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "how-to-pay-off-credit-card-debt",
      title: "How to pay off credit card debt fast (2026 playbook)",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "how to pay off credit card debt",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "capital-gains-tax-2026",
      title: "Capital gains tax 2026: Short-term vs. long-term rates explained",
      pillar: "Save tax",
      tool: "tax-bracket",
      keyword: "capital gains tax 2026",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "how-much-do-i-need-to-retire",
      title: "How much do I need to retire? (2026)",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how much do i need to retire",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
    {
      slug: "what-affects-your-credit-score",
      title: "What affects your credit score? The 5 factors explained",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "what affects credit score",
      publishedAt: "2026-05-31",
      updatedAt: "2026-05-31",
    },
  ] as const,
};
