export const siteConfig = {
  name: process.env.NEXT_PUBLIC_SITE_NAME ?? "Finbrief",
  shortName: "FB",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  description:
    "Plain-language guidance, tools, and personalized recommendations to help you budget, invest, and save smarter.",
  tagline: "Budget. Invest. Save smarter.",
  twitter: "@finbrief",
  pillars: [
    { slug: "budget", label: "Budget" },
    { slug: "invest", label: "Invest" },
    { slug: "save-tax", label: "Save tax" },
    { slug: "borrow-smart", label: "Borrow smart" },
    { slug: "protect", label: "Protect" },
  ] as const,
  tools: [
    { slug: "budget-50-30-20", label: "50/30/20 budget", pillar: "Budget" },
    { slug: "401k-match", label: "401(k) match", pillar: "Invest" },
    { slug: "tax-bracket", label: "Marginal tax rate", pillar: "Save tax" },
    { slug: "roth-vs-traditional", label: "Roth vs. Traditional IRA", pillar: "Invest" },
    { slug: "life-insurance", label: "Life insurance need", pillar: "Protect" },
  ] as const,
  articles: [
    {
      slug: "how-to-budget-50-30-20",
      title: "How to Budget Using the 50/30/20 Rule",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "50/30/20 budget",
      publishedAt: "2026-05-17",
      updatedAt: "2026-05-17",
    },
    {
      slug: "roth-ira-vs-traditional-ira",
      title: "Roth IRA vs. Traditional IRA: Which Should You Choose?",
      pillar: "Invest",
      tool: "roth-vs-traditional",
      keyword: "roth ira vs traditional ira",
      publishedAt: "2026-05-17",
      updatedAt: "2026-05-17",
    },
    {
      slug: "best-hysa-2026",
      title: "Best high-yield savings accounts 2026",
      pillar: "Budget",
      tool: "budget-50-30-20",
      keyword: "best HYSA",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "how-to-invest-1000-beginners",
      title: "How to invest $1,000 for beginners",
      pillar: "Invest",
      tool: "401k-match",
      keyword: "how to invest $1,000",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "best-term-life-insurance-young-professionals",
      title: "Best term life insurance for young professionals",
      pillar: "Protect",
      tool: "life-insurance",
      keyword: "term life insurance young professionals",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
    {
      slug: "how-to-build-credit-from-scratch",
      title: "How to build credit from scratch",
      pillar: "Borrow smart",
      tool: "tax-bracket",
      keyword: "how to build credit",
      publishedAt: "2026-05-19",
      updatedAt: "2026-05-19",
    },
  ] as const,
};
